In [1]:
print("hello world")

hello world


In [3]:
print("hello world")

hello world


In [8]:
import numpy as np

In [9]:
import numpy as np

In [10]:
arr1= np.array(["1,2,3,4,5,6,7"])
arr1

array(['1,2,3,4,5,6,7'], dtype='<U13')

In [11]:
type(arr1)

numpy.ndarray

In [12]:
arr2= np.zeros((3,3))
arr2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
arr3= np.ones((3,4))
arr3

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
arr4= np.identity(5)
arr4

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
arr5 = np.arange(10)
arr5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr6 = np.arange(5,10)
arr6

array([5, 6, 7, 8, 9])

In [17]:
arr7 = np.arange(5,10,2)
arr7

array([5, 7, 9])

In [18]:
arr7 = np.arange(1,10,3)
arr7

array([1, 4, 7])

In [19]:
arr8 = np.linspace(20,30,10)
arr8

array([20.        , 21.11111111, 22.22222222, 23.33333333, 24.44444444,
       25.55555556, 26.66666667, 27.77777778, 28.88888889, 30.        ])

In [3]:
import numpy as np


In [4]:
arr8 = np.array([1, 2, 3])
arr8

array([1, 2, 3])

In [3]:
import numpy as np

In [4]:
arr8 = np.array([1, 2, 3])
arr8

array([1, 2, 3])

In [5]:
arr9 = arr8.copy()
arr9

array([1, 2, 3])

In [6]:
arr9.shape

(3,)

In [7]:
arr10= np.array([[1,2],[3,4],[5,6],[7,8]])
arr10

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [8]:
arr10.shape

(4, 2)

In [9]:
arr11= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr11

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [10]:
arr11.shape

(2, 2, 2)

#### To check the dimension of the metrix we use [ndim]


In [11]:
arr11.ndim

3

In [12]:
arr12= np.array([[1,2],[3,4]])
arr12

array([[1, 2],
       [3, 4]])

In [13]:
arr12.ndim

2

In [15]:
arr13 = np.array([1, 2, 3])
arr13

array([1, 2, 3])

In [16]:
arr13.ndim

1

#### Size is number of items in a matrix

In [17]:
arr11.size

8

In [18]:
arr12.size

4

In [19]:
arr12.itemsize

8

In [24]:
arr12.dtype

dtype('int64')

In [22]:
arr13= np.arange(24).reshape(6,4)
arr13

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### **Slicing [rows, cols]**

Rows 2:4 → take rows with indices 2 and 3 (not 4):

Row 2 → _[ 8, 9, 10, 11]_

Row 3 → _[12, 13, 14, 15]_

Columns 1:3 → take columns with indices 1 and 2 (not 3):

From each selected row, keep only Col1 and Col2.
Apply to the rows:

Row 2, columns 1..2 → _[9, 10]_

Row 3, columns 1..2 → _[13, 14]_

Stack those rows together →

In [23]:
arr13[2:4,1:3]

array([[ 9, 10],
       [13, 14]])


###### : is taking all the rows


In [25]:
arr13[:,2:4]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])

### Iteration

In [26]:
for i in arr13:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [27]:
for i in np.nditer(arr13):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


#### Array Operation

In [28]:
import numpy as np

In [34]:
arr1= np.arange(1,7)
arr2= np.array([7,8,9,10,11,12])
arr1

array([1, 2, 3, 4, 5, 6])

In [33]:
arr2

array([ 7,  8,  9, 10, 11, 12])

In [35]:
arr1-arr2

array([-6, -6, -6, -6, -6, -6])

In [37]:
arr1*arr2

array([ 7, 16, 27, 40, 55, 72])

In [38]:
arr1*2

array([ 2,  4,  6,  8, 10, 12])

In [40]:
arr2>10

array([False, False, False, False,  True,  True])

In [45]:
arr3=np.arange(6).reshape(2,3)
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [49]:
arr4=np.arange(6,12).reshape(3,2)
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [50]:
arr3.dot(arr4)

array([[ 28,  31],
       [100, 112]])

In [51]:
arr4.max()

np.int64(11)

In [52]:
arr4.min()

np.int64(6)

In [53]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

Giving collum wise min

In [54]:
arr4.min(axis=0)

array([6, 7])

Giving row wise min

In [55]:
arr4.min(axis=1)

array([ 6,  8, 10])

In [56]:
arr4.sum()

np.int64(51)

In [57]:
arr4.sum(axis=0)

array([24, 27])

In [58]:
arr4.sum(axis=1)

array([13, 17, 21])

In [59]:
arr4.mean()

np.float64(8.5)

In [60]:
arr4.mean(axis=0)

array([8., 9.])

In [61]:
arr4.std()

np.float64(1.707825127659933)

In [62]:
np.sin(arr4)

array([[-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849],
       [-0.54402111, -0.99999021]])

In [63]:
np.median(arr4)

np.float64(8.5)

In [64]:
np.exp(arr4)

array([[  403.42879349,  1096.63315843],
       [ 2980.95798704,  8103.08392758],
       [22026.46579481, 59874.1417152 ]])